### ISSUE TITLE
Publish to Windows Package Managar (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [GeoffreyChen777/paperlib#130]
With every new release of paperlib, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

Existing projects which use the action: https://github.com/search?q=vedantmgoyal2009%2Fwinget-releaser+path%3A.github%2Fworkflows%2F+language%3AYAML&type=Code&s=indexed&o=desc

**Comment by GeoffreyChen777** [comment]
I got this error:

```
D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:216
        throw new Error(`Input required and not supplied: ${name}`);
              ^
Error: Input required and not supplied: release-tag
    at getInput (D:\a\_actions\vedantmgoyal[2](https://github.com/GeoffreyChen777/paperlib/runs/8052690778?check_suite_focus=true#step:2:2)009\winget-releaser\latest\dist\index.js:216:15)
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9041:24
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9129:[3](https://github.com/GeoffreyChen777/paperlib/runs/8052690778?check_suite_focus=true#step:2:3)
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9131:3
    at Object.<anonymous> (D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:913[4](https://github.com/GeoffreyChen777/paperlib/runs/8052690778?check_suite_focus=true#step:2:4):12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:11[5](https://github.com/GeoffreyChen777/paperlib/runs/8052690778?check_suite_focus=true#step:2:5)3:10)
    at Module.load (node:internal/modules/cjs/loader:9[8](https://github.com/GeoffreyChen777/paperlib/runs/8052690778?check_suite_focus=true#step:2:8)1:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/GeoffreyChen777/paperlib/runs/8052690778?check_suite_focus=true#step:2:12))
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

any suggestions?

**Comment by vedantmgoyal2009** [comment]
The issue was fixed but I forgot to reply. Can you please re-publish the latest release to confirm if it's working.
![image](https://user-images.githubusercontent.com/83997633/188262590-a366fade-e88c-438c-a10b-08aa5ef3335c.png)

And then,

![image](https://user-images.githubusercontent.com/83997633/188262613-adcaee33-68cc-49aa-88d4-5378098ec1e3.png)
